version: '3'

services:
  app:
    # Uncomment the next line to use a non-root user. See https://aka.ms/vscode-remote/containers/non-root-user.
    # user: 1000

    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # ports:
    #  - 8000:8000

    links: 
      - db
    
  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: LocalPassword
