# Generated by Django 2.2.1 on 2019-08-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=7, unique=True)),
                ('make', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('year', models.DateField()),
                ('currently_with', models.CharField(choices=[('BR', 'Branch'), ('DR', 'Driver')], default='Branch', max_length=2)),
                ('in_service', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
    ]
