# Generated by Django 2.2.1 on 2019-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottoapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
